"""Persistence for alert rules, per-rule fired-state (dedup), and alert history.

Speaks two dialects from one module:
  config.DATABASE_URL set   -> PostgreSQL via psycopg3 (Vercel / any serverless host)
  config.DATABASE_URL unset -> SQLite on local disk (dev, Docker, the test suite)

The backend is resolved per call, not at import, so tests can repoint
config.DB_FILE / config.DATABASE_URL after this module is imported.

Concurrency-safe: SQLite gets WAL plus a write lock; PostgreSQL gets MVCC. The
False->True edge in record_transition is claimed with a conditional UPDATE, so
two overlapping cycles cannot both decide they fired first.
"""
import json
import sqlite3
import threading
import time
from contextlib import contextmanager
from datetime import datetime
from zoneinfo import ZoneInfo

import config

ET = ZoneInfo("America/New_York")
_write_lock = threading.Lock()


def _is_pg():
    return bool(config.DATABASE_URL)


def _exec(conn, sql, params=()):
    """Run SQL written in the SQLite dialect against whichever backend is active.

    Only the placeholder style differs at the call sites; no SQL string in this
    module contains a literal '?', so the rewrite is unambiguous.
    """
    if _is_pg():
        sql = sql.replace("?", "%s")
    return conn.execute(sql, params)


@contextmanager
def _db(write=False):
    if _is_pg():
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(config.DATABASE_URL, row_factory=dict_row, connect_timeout=10)
    else:
        conn = sqlite3.connect(config.DB_FILE, timeout=10)
        conn.row_factory = sqlite3.Row
    try:
        if write:
            _write_lock.acquire()
        yield conn
        if write:
            conn.commit()
    finally:
        if write:
            _write_lock.release()
        conn.close()


def init():
    pg = _is_pg()
    if not pg:
        config.DB_FILE.parent.mkdir(parents=True, exist_ok=True)
    # dialect-specific column types; everything else is identical SQL
    serial = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    real = "DOUBLE PRECISION" if pg else "REAL"
    bigint = "BIGINT" if pg else "INTEGER"
    with _db(write=True) as c:
        if not pg:
            _exec(c, "PRAGMA journal_mode=WAL")
        _exec(c, """CREATE TABLE IF NOT EXISTS rules(
            id TEXT PRIMARY KEY, name TEXT, symbol TEXT, timeframe TEXT,
            condition TEXT, enabled INTEGER DEFAULT 1, created_at TEXT)""")
        _exec(c, f"""CREATE TABLE IF NOT EXISTS rule_state(
            rule_id TEXT PRIMARY KEY, fired INTEGER DEFAULT 0,
            last_value {real}, last_fired_at TEXT)""")
        _exec(c, f"""CREATE TABLE IF NOT EXISTS alerts(
            id {serial}, rule_id TEXT, name TEXT,
            symbol TEXT, timeframe TEXT, description TEXT,
            value {real}, price {real}, ts TEXT, ts_ms {bigint})""")
        _exec(c, "CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT)")
        if not pg:
            # migrate older SQLite files that predate ts_ms (epoch ms for "triggered X ago").
            # Fresh databases of either dialect already declare the column above.
            if "ts_ms" not in [r["name"] for r in _exec(c, "PRAGMA table_info(alerts)")]:
                _exec(c, "ALTER TABLE alerts ADD COLUMN ts_ms INTEGER")


def get_setting(key, default=None):
    with _db() as c:
        r = _exec(c, "SELECT value FROM settings WHERE key=?", (key,)).fetchone()
        return r["value"] if r else default


def set_setting(key, value):
    with _db(write=True) as c:
        _exec(c, "INSERT INTO settings(key,value) VALUES(?,?) "
                 "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (key, str(value)))


def claim_once(key):
    """Atomically claim a one-time action; True for the first caller only.

    Two serverless cold starts can race to seed the database — a plain
    check-then-act leaves the loser inserting a duplicate set of rules.
    """
    with _db(write=True) as c:
        cur = _exec(c, "INSERT INTO settings(key,value) VALUES(?,'1') "
                       "ON CONFLICT(key) DO NOTHING", (key,))
        return cur.rowcount == 1


def _row_to_rule(r):
    return {
        "id": r["id"], "name": r["name"], "symbol": r["symbol"], "timeframe": r["timeframe"],
        "condition": json.loads(r["condition"]), "enabled": bool(r["enabled"]),
        "created_at": r["created_at"],
    }


def list_rules(enabled_only=False):
    q = "SELECT * FROM rules"
    if enabled_only:
        q += " WHERE enabled=1"
    q += " ORDER BY created_at"
    with _db() as c:
        return [_row_to_rule(r) for r in _exec(c, q)]


def get_rule(rid):
    with _db() as c:
        r = _exec(c, "SELECT * FROM rules WHERE id=?", (rid,)).fetchone()
        return _row_to_rule(r) if r else None


def create_rule(rule):
    with _db(write=True) as c:
        _exec(c,
              "INSERT INTO rules(id,name,symbol,timeframe,condition,enabled,created_at) VALUES(?,?,?,?,?,?,?)",
              (rule["id"], rule["name"], rule["symbol"], rule["timeframe"],
               json.dumps(rule["condition"]), int(rule.get("enabled", True)),
               datetime.now(ET).isoformat()))
    return get_rule(rule["id"])


def update_rule(rid, rule):
    with _db(write=True) as c:
        _exec(c,
              "UPDATE rules SET name=?,symbol=?,timeframe=?,condition=?,enabled=? WHERE id=?",
              (rule["name"], rule["symbol"], rule["timeframe"], json.dumps(rule["condition"]),
               int(rule.get("enabled", True)), rid))
    return get_rule(rid)


def delete_rule(rid):
    with _db(write=True) as c:
        _exec(c, "DELETE FROM rules WHERE id=?", (rid,))
        _exec(c, "DELETE FROM rule_state WHERE rule_id=?", (rid,))


def record_transition(rule_id, fired, value):
    """Persist fired-state; return True only on a fresh False->True edge (a new alert).

    The edge is claimed by an UPDATE guarded on `fired=0`, so exactly one caller
    can win it even if two evaluation cycles overlap.
    """
    now = datetime.now(ET).isoformat()
    with _db(write=True) as c:
        _exec(c, "INSERT INTO rule_state(rule_id,fired,last_value) VALUES(?,0,NULL) "
                 "ON CONFLICT(rule_id) DO NOTHING", (rule_id,))
        if not fired:
            _exec(c, "UPDATE rule_state SET fired=0,last_value=? WHERE rule_id=?", (value, rule_id))
            return False
        cur = _exec(c, "UPDATE rule_state SET fired=1,last_value=?,last_fired_at=? "
                       "WHERE rule_id=? AND fired=0", (value, now, rule_id))
        if cur.rowcount == 1:
            return True
        _exec(c, "UPDATE rule_state SET last_value=? WHERE rule_id=?", (value, rule_id))
        return False


def append_alert(rule, description, value, price):
    with _db(write=True) as c:
        _exec(c,
              "INSERT INTO alerts(rule_id,name,symbol,timeframe,description,value,price,ts,ts_ms) "
              "VALUES(?,?,?,?,?,?,?,?,?)",
              (rule["id"], rule["name"], rule["symbol"], rule["timeframe"], description, value, price,
               datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S ET"), int(time.time() * 1000)))


def list_alerts(limit=50):
    limit = max(1, min(int(limit), 500))  # bounded: the table grows without limit
    with _db() as c:
        return [dict(r) for r in _exec(c, "SELECT * FROM alerts ORDER BY id DESC LIMIT ?", (limit,))]


# --- dead-man heartbeat ----------------------------------------------------
# Lives in the DB, not a module global: on serverless every request is a fresh
# process, and an in-memory heartbeat would reset to "healthy" on every cold
# start — a permanently green lie about a monitor that stopped running.

def mark_success():
    set_setting("last_success_ms", int(time.time() * 1000))


def last_success_ms():
    v = get_setting("last_success_ms")
    return int(v) if v else None


def stale_seconds():
    """Seconds since the last healthy cycle, or None if one has never landed."""
    ms = last_success_ms()
    return None if ms is None else max(0.0, time.time() - ms / 1000.0)
