"""Persistence for alert rules, per-rule fired-state (dedup), and alert history.

Speaks two dialects from one module:
  config.DATABASE_URL set   -> PostgreSQL via psycopg3 (Vercel / any serverless host)
  config.DATABASE_URL unset -> SQLite on local disk (dev, Docker, the test suite)

The backend is resolved per call, not at import, so tests can repoint
config.DB_FILE / config.DATABASE_URL after this module is imported.

Concurrency-safe: SQLite gets WAL plus a write lock; PostgreSQL gets MVCC. The
False->True edge in record_transition is claimed with a conditional UPDATE, so
two overlapping cycles cannot both decide they fired first.
"""
import json
import sqlite3
import threading
import time
from contextlib import contextmanager
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import config

ET = ZoneInfo("America/New_York")
_write_lock = threading.Lock()


def _is_pg():
    return bool(config.DATABASE_URL)


def _exec(conn, sql, params=()):
    """Run SQL written in the SQLite dialect against whichever backend is active.

    Only the placeholder style differs at the call sites; no SQL string in this
    module contains a literal '?', so the rewrite is unambiguous.
    """
    if _is_pg():
        sql = sql.replace("?", "%s")
    return conn.execute(sql, params)


def _connect():
    if _is_pg():
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(config.DATABASE_URL, row_factory=dict_row, connect_timeout=10)
        # Serverless means a new connection per request, so the DSN should point at a
        # transaction pooler (Supabase/Supavisor port 6543, pgbouncer, …). Those do not
        # support prepared statements, and psycopg auto-prepares a query after the 5th
        # execution — which would start failing only once traffic warmed up.
        conn.prepare_threshold = None
    else:
        conn = sqlite3.connect(config.DB_FILE, timeout=10)
        conn.row_factory = sqlite3.Row
    return conn


# One evaluation cycle used to open a fresh connection per db call — N+F+Uf+U+4 of
# them, each a full TLS+auth handshake through the pooler. `session()` lends the
# whole cycle a single connection that `_db()` reuses. Commit boundaries are
# unchanged: every write still commits at the end of its own `_db(write=True)`
# block, so a mid-cycle kill leaves exactly what it left before.
_ambient = threading.local()


@contextmanager
def session():
    """Reuse one connection for every _db() call on this thread."""
    if getattr(_ambient, "conn", None) is not None:
        yield  # already inside a session; do not nest or double-close
        return
    _ambient.conn = _connect()
    try:
        yield
    finally:
        conn, _ambient.conn = _ambient.conn, None
        conn.close()


@contextmanager
def _db(write=False):
    borrowed = getattr(_ambient, "conn", None)
    conn = borrowed or _connect()
    try:
        if write:
            _write_lock.acquire()
        yield conn
        if write:
            conn.commit()
    finally:
        if write:
            _write_lock.release()
        # A borrowed connection belongs to session(); closing it here would pull it
        # out from under every later call in the same cycle.
        if borrowed is None:
            conn.close()


def init():
    pg = _is_pg()
    if not pg:
        config.DB_FILE.parent.mkdir(parents=True, exist_ok=True)
    # dialect-specific column types; everything else is identical SQL
    serial = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    real = "DOUBLE PRECISION" if pg else "REAL"
    bigint = "BIGINT" if pg else "INTEGER"
    with _db(write=True) as c:
        if not pg:
            _exec(c, "PRAGMA journal_mode=WAL")
        _exec(c, """CREATE TABLE IF NOT EXISTS rules(
            id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT, symbol TEXT, timeframe TEXT,
            condition TEXT, enabled INTEGER DEFAULT 1, created_at TEXT)""")
        # rule_state is NOT user-scoped, on purpose: rule ids are uuid4-derived and
        # globally unique, and rule_id is this table's primary key, so per-rule dedup
        # already IS per-user dedup. Adding user_id would widen the edge-claim
        # predicate without changing which row it hits.
        _exec(c, f"""CREATE TABLE IF NOT EXISTS rule_state(
            rule_id TEXT PRIMARY KEY, fired INTEGER DEFAULT 0,
            last_value {real}, last_fired_at TEXT)""")
        # alerts carry their own user_id rather than joining rules: delete_rule
        # deliberately leaves history behind, and a join would erase it.
        # `sent`/`attempts` make delivery an outbox: history is written before the
        # email is attempted, so without them a cycle killed at the 60s ceiling (or a
        # Resend 5xx) leaves the rule latched, the alert in history, and no mail ever.
        _exec(c, f"""CREATE TABLE IF NOT EXISTS alerts(
            id {serial}, user_id TEXT NOT NULL, rule_id TEXT, name TEXT,
            symbol TEXT, timeframe TEXT, description TEXT,
            value {real}, price {real}, ts TEXT, ts_ms {bigint},
            sent INTEGER NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0)""")
        _exec(c, "CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT)")
        if pg:
            # The deployed tables predate per-user accounts and CREATE TABLE IF NOT
            # EXISTS skips them, so migrate in place. Idempotent and additive, which
            # beats a manual DROP + redeploy: that has a window where a warm process
            # answers requests against tables that no longer exist.
            _exec(c, "ALTER TABLE rules  ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT ''")
            _exec(c, "ALTER TABLE alerts ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT ''")
            # DEFAULT 1 on the migration path ONLY: every pre-existing alert is
            # historical and was already delivered (or already missed). Defaulting
            # them to 0 would re-email the entire history on first deploy.
            # append_alert always passes `sent` explicitly, so new rows are unaffected.
            _exec(c, "ALTER TABLE alerts ADD COLUMN IF NOT EXISTS sent INTEGER NOT NULL DEFAULT 1")
            _exec(c, "ALTER TABLE alerts ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0")
        if not pg:
            # migrate older SQLite files: ts_ms (epoch ms for "triggered X ago") and
            # user_id both postdate existing dev databases, and CREATE TABLE IF NOT
            # EXISTS silently skips them. Fresh databases declare both above.
            acols = {r["name"] for r in _exec(c, "PRAGMA table_info(alerts)")}
            if "ts_ms" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN ts_ms INTEGER")
            # DEFAULT '' only on the migration path: SQLite requires one, and rows
            # owned by nobody are invisible to every account until adopted by hand.
            if "user_id" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN user_id TEXT NOT NULL DEFAULT ''")
            # See the Postgres branch: DEFAULT 1 so existing history is not re-sent.
            if "sent" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN sent INTEGER NOT NULL DEFAULT 1")
            if "attempts" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0")
            if "user_id" not in {r["name"] for r in _exec(c, "PRAGMA table_info(rules)")}:
                _exec(c, "ALTER TABLE rules ADD COLUMN user_id TEXT NOT NULL DEFAULT ''")
        # AFTER the migration, never before: on a pre-existing database the columns
        # these index do not exist until the ALTERs above have run.
        _exec(c, "CREATE INDEX IF NOT EXISTS idx_rules_user ON rules(user_id)")
        _exec(c, "CREATE INDEX IF NOT EXISTS idx_alerts_user ON alerts(user_id, id DESC)")


def get_setting(key, default=None):
    with _db() as c:
        r = _exec(c, "SELECT value FROM settings WHERE key=?", (key,)).fetchone()
        return r["value"] if r else default


def set_setting(key, value):
    with _db(write=True) as c:
        _exec(c, "INSERT INTO settings(key,value) VALUES(?,?) "
                 "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (key, str(value)))


def prune_cycle_claims(keep_after):
    """Drop spent boundary claims so the settings table does not grow forever.

    Called from the market-closed branch: off-hours, once per ping, one DELETE.
    Keys are `cycle:<epoch-minute>`. Epoch minutes are 8 digits from 2009 until
    ~2160, so within that window a lexical compare and a numeric one agree and the
    plain `<` is safe.
    """
    with _db(write=True) as c:
        _exec(c, "DELETE FROM settings WHERE key LIKE 'cycle:%' AND key < ?",
              (f"cycle:{keep_after}",))


def claim_once(key):
    """Atomically claim a one-time action; True for the first caller only.

    Two serverless cold starts can race to seed the database — a plain
    check-then-act leaves the loser inserting a duplicate set of rules.
    """
    with _db(write=True) as c:
        cur = _exec(c, "INSERT INTO settings(key,value) VALUES(?,'1') "
                       "ON CONFLICT(key) DO NOTHING", (key,))
        return cur.rowcount == 1


# --- per-user settings -----------------------------------------------------
# Bare keys stay SYSTEM state (snapshot heartbeat, deadman_fired, seeded); user
# state is namespaced. The id is a server-supplied uuid, so "u:<uuid>:<name>"
# can never collide with a system key. No scope column, no second table.

def ukey(user_id, name):
    return f"u:{user_id}:{name}"


def user_recipients(user_id):
    v = get_setting(ukey(user_id, "recipients"))
    return [e.strip() for e in v.split(",") if e.strip()] if v else []


def set_user_recipients(user_id, emails):
    set_setting(ukey(user_id, "recipients"), ",".join(emails))


def _row_to_rule(r):
    return {
        "id": r["id"], "user_id": r["user_id"], "name": r["name"], "symbol": r["symbol"],
        "timeframe": r["timeframe"], "condition": json.loads(r["condition"]),
        "enabled": bool(r["enabled"]), "created_at": r["created_at"],
    }


# user_id is a REQUIRED positional on every user-facing read. A `user_id=None
# means all` default would turn one forgotten argument into a silent cross-user
# leak; the engine's cross-user read gets its own name instead.

def list_rules(user_id, enabled_only=False):
    q = "SELECT * FROM rules WHERE user_id=?"
    if enabled_only:
        q += " AND enabled=1"
    q += " ORDER BY created_at"
    with _db() as c:
        return [_row_to_rule(r) for r in _exec(c, q, (user_id,))]


def all_enabled_rules():
    """Every user's enabled rules — the evaluation cycle, and nothing else."""
    with _db() as c:
        return [_row_to_rule(r) for r in
                _exec(c, "SELECT * FROM rules WHERE enabled=1 ORDER BY created_at")]


def get_rule(rid, user_id):
    with _db() as c:
        r = _exec(c, "SELECT * FROM rules WHERE id=? AND user_id=?", (rid, user_id)).fetchone()
        return _row_to_rule(r) if r else None


def create_rule(rule, user_id):
    with _db(write=True) as c:
        _exec(c,
              "INSERT INTO rules(id,user_id,name,symbol,timeframe,condition,enabled,created_at) "
              "VALUES(?,?,?,?,?,?,?,?)",
              (rule["id"], user_id, rule["name"], rule["symbol"], rule["timeframe"],
               json.dumps(rule["condition"]), int(rule.get("enabled", True)),
               datetime.now(ET).isoformat()))
    return get_rule(rule["id"], user_id)


def update_rule(rid, rule, user_id):
    with _db(write=True) as c:
        _exec(c,
              "UPDATE rules SET name=?,symbol=?,timeframe=?,condition=?,enabled=? "
              "WHERE id=? AND user_id=?",
              (rule["name"], rule["symbol"], rule["timeframe"], json.dumps(rule["condition"]),
               int(rule.get("enabled", True)), rid, user_id))
    return get_rule(rid, user_id)


def delete_rule(rid, user_id):
    with _db(write=True) as c:
        cur = _exec(c, "DELETE FROM rules WHERE id=? AND user_id=?", (rid, user_id))
        # only clear dedup state if OUR row actually went: an unscoped delete here
        # lets a foreign delete attempt un-latch someone else's rule and re-alert them
        if cur.rowcount:
            _exec(c, "DELETE FROM rule_state WHERE rule_id=?", (rid,))


def record_transition(rule_id, fired, value):
    """Persist fired-state; return True when the rule should alert.

    That is a fresh False->True edge, claimed by an UPDATE guarded on `fired=0`, so
    exactly one caller wins it even if two evaluation cycles overlap.

    A rule whose condition simply STAYS true would otherwise alert once and go
    silent forever — RSI parked below 15 for three days is one email. So a latched
    rule re-arms once RULE_COOLDOWN_MINUTES have passed since it last fired. The
    re-claim carries its own `last_fired_at <= cutoff` guard, which makes it exactly
    as atomic as the edge claim: two concurrent cycles cannot both win it.
    Set RULE_COOLDOWN_MINUTES=0 to restore pure edge-triggered firing.
    """
    now_dt = datetime.now(ET)
    now = now_dt.isoformat()
    with _db(write=True) as c:
        _exec(c, "INSERT INTO rule_state(rule_id,fired,last_value) VALUES(?,0,NULL) "
                 "ON CONFLICT(rule_id) DO NOTHING", (rule_id,))
        if not fired:
            _exec(c, "UPDATE rule_state SET fired=0,last_value=? WHERE rule_id=?", (value, rule_id))
            return False
        cur = _exec(c, "UPDATE rule_state SET fired=1,last_value=?,last_fired_at=? "
                       "WHERE rule_id=? AND fired=0", (value, now, rule_id))
        if cur.rowcount == 1:
            return True
        cooldown = config.RULE_COOLDOWN_MINUTES
        if cooldown > 0:
            cutoff = (now_dt - timedelta(minutes=cooldown)).isoformat()
            # last_fired_at is TEXT ISO-8601 in a fixed offset-aware format, so a
            # lexical <= is a chronological one.
            cur = _exec(c, "UPDATE rule_state SET last_value=?,last_fired_at=? "
                           "WHERE rule_id=? AND fired=1 AND last_fired_at IS NOT NULL "
                           "AND last_fired_at<=?", (value, now, rule_id, cutoff))
            if cur.rowcount == 1:
                return True
        _exec(c, "UPDATE rule_state SET last_value=? WHERE rule_id=?", (value, rule_id))
        return False


def append_alert(rule, description, value, price):
    """Record a fired alert as UNSENT and return its id.

    `sent` is passed explicitly (never left to the column default) because the
    migration adds that column with DEFAULT 1 to spare pre-existing history from
    being re-emailed. New rows must start at 0 regardless.
    """
    # rule["user_id"], not .get(): an alert with no owner is one nobody can ever
    # see, and it should fail in tests rather than vanish in production.
    sql = ("INSERT INTO alerts(user_id,rule_id,name,symbol,timeframe,description,value,price,ts,ts_ms,sent,attempts) "
           "VALUES(?,?,?,?,?,?,?,?,?,?,0,0)")
    params = (rule["user_id"], rule["id"], rule["name"], rule["symbol"], rule["timeframe"],
              description, value, price,
              datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S ET"), int(time.time() * 1000))
    with _db(write=True) as c:
        if _is_pg():
            return _exec(c, sql + " RETURNING id", params).fetchone()["id"]
        return _exec(c, sql, params).lastrowid


def unsent_alerts(max_attempts=None, max_age_minutes=None):
    """Alerts written but not yet delivered, oldest first.

    Bounded on both attempts and age so a permanently failing alert (bad recipient,
    Resend rejecting the payload) eventually stops being retried instead of
    wedging every later cycle behind it.
    """
    max_attempts = config.DELIVERY_MAX_ATTEMPTS if max_attempts is None else max_attempts
    max_age_minutes = config.DELIVERY_MAX_AGE_MINUTES if max_age_minutes is None else max_age_minutes
    floor_ms = int((time.time() - max_age_minutes * 60) * 1000)
    with _db() as c:
        return [dict(r) for r in _exec(
            c, "SELECT * FROM alerts WHERE sent=0 AND attempts<? AND ts_ms>=? ORDER BY id",
            (max_attempts, floor_ms))]


def mark_alerts_sent(ids):
    if not ids:
        return
    with _db(write=True) as c:
        for aid in ids:  # ponytail: per-id UPDATE; one statement per alert is fine at this volume
            _exec(c, "UPDATE alerts SET sent=1 WHERE id=?", (aid,))


def bump_attempts(ids):
    if not ids:
        return
    with _db(write=True) as c:
        for aid in ids:
            _exec(c, "UPDATE alerts SET attempts=attempts+1 WHERE id=?", (aid,))


def list_alerts(user_id, limit=50):
    limit = max(1, min(int(limit), 500))  # bounded: the table grows without limit
    with _db() as c:
        return [dict(r) for r in _exec(
            c, "SELECT * FROM alerts WHERE user_id=? ORDER BY id DESC LIMIT ?", (user_id, limit))]


# --- dead-man heartbeat ----------------------------------------------------
# Lives in the DB, not a module global: on serverless every request is a fresh
# process, and an in-memory heartbeat would reset to "healthy" on every cold
# start — a permanently green lie about a monitor that stopped running.

def mark_success():
    set_setting("last_success_ms", int(time.time() * 1000))


def last_success_ms():
    v = get_setting("last_success_ms")
    return int(v) if v else None


def stale_seconds():
    """Seconds since the last healthy cycle, or None if one has never landed."""
    ms = last_success_ms()
    return None if ms is None else max(0.0, time.time() - ms / 1000.0)
