"""Persistence for alert rules, per-rule fired-state (dedup), and alert history.

Speaks two dialects from one module:
  config.DATABASE_URL set   -> PostgreSQL via psycopg3 (Vercel / any serverless host)
  config.DATABASE_URL unset -> SQLite on local disk (dev, Docker, the test suite)

The backend is resolved per call, not at import, so tests can repoint
config.DB_FILE / config.DATABASE_URL after this module is imported.

Concurrency-safe: SQLite gets WAL plus a write lock; PostgreSQL gets MVCC. The
False->True edge in record_transition is claimed with a conditional UPDATE, so
two overlapping cycles cannot both decide they fired first.
"""
import json
import sqlite3
import threading
import time
from contextlib import contextmanager
from datetime import datetime
from zoneinfo import ZoneInfo

import config

ET = ZoneInfo("America/New_York")
_write_lock = threading.Lock()


def _is_pg():
    return bool(config.DATABASE_URL)


def _exec(conn, sql, params=()):
    """Run SQL written in the SQLite dialect against whichever backend is active.

    Only the placeholder style differs at the call sites; no SQL string in this
    module contains a literal '?', so the rewrite is unambiguous.
    """
    if _is_pg():
        sql = sql.replace("?", "%s")
    return conn.execute(sql, params)


@contextmanager
def _db(write=False):
    if _is_pg():
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(config.DATABASE_URL, row_factory=dict_row, connect_timeout=10)
        # Serverless means a new connection per request, so the DSN should point at a
        # transaction pooler (Supabase/Supavisor port 6543, pgbouncer, …). Those do not
        # support prepared statements, and psycopg auto-prepares a query after the 5th
        # execution — which would start failing only once traffic warmed up.
        conn.prepare_threshold = None
    else:
        conn = sqlite3.connect(config.DB_FILE, timeout=10)
        conn.row_factory = sqlite3.Row
    try:
        if write:
            _write_lock.acquire()
        yield conn
        if write:
            conn.commit()
    finally:
        if write:
            _write_lock.release()
        conn.close()


def init():
    pg = _is_pg()
    if not pg:
        config.DB_FILE.parent.mkdir(parents=True, exist_ok=True)
    # dialect-specific column types; everything else is identical SQL
    serial = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    real = "DOUBLE PRECISION" if pg else "REAL"
    bigint = "BIGINT" if pg else "INTEGER"
    with _db(write=True) as c:
        if not pg:
            _exec(c, "PRAGMA journal_mode=WAL")
        _exec(c, """CREATE TABLE IF NOT EXISTS rules(
            id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT, symbol TEXT, timeframe TEXT,
            condition TEXT, enabled INTEGER DEFAULT 1, created_at TEXT)""")
        # rule_state is NOT user-scoped, on purpose: rule ids are uuid4-derived and
        # globally unique, and rule_id is this table's primary key, so per-rule dedup
        # already IS per-user dedup. Adding user_id would widen the edge-claim
        # predicate without changing which row it hits.
        _exec(c, f"""CREATE TABLE IF NOT EXISTS rule_state(
            rule_id TEXT PRIMARY KEY, fired INTEGER DEFAULT 0,
            last_value {real}, last_fired_at TEXT)""")
        # alerts carry their own user_id rather than joining rules: delete_rule
        # deliberately leaves history behind, and a join would erase it.
        _exec(c, f"""CREATE TABLE IF NOT EXISTS alerts(
            id {serial}, user_id TEXT NOT NULL, rule_id TEXT, name TEXT,
            symbol TEXT, timeframe TEXT, description TEXT,
            value {real}, price {real}, ts TEXT, ts_ms {bigint})""")
        _exec(c, "CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT)")
        if pg:
            # The deployed tables predate per-user accounts and CREATE TABLE IF NOT
            # EXISTS skips them, so migrate in place. Idempotent and additive, which
            # beats a manual DROP + redeploy: that has a window where a warm process
            # answers requests against tables that no longer exist.
            _exec(c, "ALTER TABLE rules  ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT ''")
            _exec(c, "ALTER TABLE alerts ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT ''")
        if not pg:
            # migrate older SQLite files: ts_ms (epoch ms for "triggered X ago") and
            # user_id both postdate existing dev databases, and CREATE TABLE IF NOT
            # EXISTS silently skips them. Fresh databases declare both above.
            acols = {r["name"] for r in _exec(c, "PRAGMA table_info(alerts)")}
            if "ts_ms" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN ts_ms INTEGER")
            # DEFAULT '' only on the migration path: SQLite requires one, and rows
            # owned by nobody are invisible to every account until adopted by hand.
            if "user_id" not in acols:
                _exec(c, "ALTER TABLE alerts ADD COLUMN user_id TEXT NOT NULL DEFAULT ''")
            if "user_id" not in {r["name"] for r in _exec(c, "PRAGMA table_info(rules)")}:
                _exec(c, "ALTER TABLE rules ADD COLUMN user_id TEXT NOT NULL DEFAULT ''")
        # AFTER the migration, never before: on a pre-existing database the columns
        # these index do not exist until the ALTERs above have run.
        _exec(c, "CREATE INDEX IF NOT EXISTS idx_rules_user ON rules(user_id)")
        _exec(c, "CREATE INDEX IF NOT EXISTS idx_alerts_user ON alerts(user_id, id DESC)")


def get_setting(key, default=None):
    with _db() as c:
        r = _exec(c, "SELECT value FROM settings WHERE key=?", (key,)).fetchone()
        return r["value"] if r else default


def set_setting(key, value):
    with _db(write=True) as c:
        _exec(c, "INSERT INTO settings(key,value) VALUES(?,?) "
                 "ON CONFLICT(key) DO UPDATE SET value=excluded.value", (key, str(value)))


def claim_once(key):
    """Atomically claim a one-time action; True for the first caller only.

    Two serverless cold starts can race to seed the database — a plain
    check-then-act leaves the loser inserting a duplicate set of rules.
    """
    with _db(write=True) as c:
        cur = _exec(c, "INSERT INTO settings(key,value) VALUES(?,'1') "
                       "ON CONFLICT(key) DO NOTHING", (key,))
        return cur.rowcount == 1


# --- per-user settings -----------------------------------------------------
# Bare keys stay SYSTEM state (snapshot heartbeat, deadman_fired, seeded); user
# state is namespaced. The id is a server-supplied uuid, so "u:<uuid>:<name>"
# can never collide with a system key. No scope column, no second table.

def ukey(user_id, name):
    return f"u:{user_id}:{name}"


def user_recipients(user_id):
    v = get_setting(ukey(user_id, "recipients"))
    return [e.strip() for e in v.split(",") if e.strip()] if v else []


def set_user_recipients(user_id, emails):
    set_setting(ukey(user_id, "recipients"), ",".join(emails))


def _row_to_rule(r):
    return {
        "id": r["id"], "user_id": r["user_id"], "name": r["name"], "symbol": r["symbol"],
        "timeframe": r["timeframe"], "condition": json.loads(r["condition"]),
        "enabled": bool(r["enabled"]), "created_at": r["created_at"],
    }


# user_id is a REQUIRED positional on every user-facing read. A `user_id=None
# means all` default would turn one forgotten argument into a silent cross-user
# leak; the engine's cross-user read gets its own name instead.

def list_rules(user_id, enabled_only=False):
    q = "SELECT * FROM rules WHERE user_id=?"
    if enabled_only:
        q += " AND enabled=1"
    q += " ORDER BY created_at"
    with _db() as c:
        return [_row_to_rule(r) for r in _exec(c, q, (user_id,))]


def all_enabled_rules():
    """Every user's enabled rules — the evaluation cycle, and nothing else."""
    with _db() as c:
        return [_row_to_rule(r) for r in
                _exec(c, "SELECT * FROM rules WHERE enabled=1 ORDER BY created_at")]


def get_rule(rid, user_id):
    with _db() as c:
        r = _exec(c, "SELECT * FROM rules WHERE id=? AND user_id=?", (rid, user_id)).fetchone()
        return _row_to_rule(r) if r else None


def create_rule(rule, user_id):
    with _db(write=True) as c:
        _exec(c,
              "INSERT INTO rules(id,user_id,name,symbol,timeframe,condition,enabled,created_at) "
              "VALUES(?,?,?,?,?,?,?,?)",
              (rule["id"], user_id, rule["name"], rule["symbol"], rule["timeframe"],
               json.dumps(rule["condition"]), int(rule.get("enabled", True)),
               datetime.now(ET).isoformat()))
    return get_rule(rule["id"], user_id)


def update_rule(rid, rule, user_id):
    with _db(write=True) as c:
        _exec(c,
              "UPDATE rules SET name=?,symbol=?,timeframe=?,condition=?,enabled=? "
              "WHERE id=? AND user_id=?",
              (rule["name"], rule["symbol"], rule["timeframe"], json.dumps(rule["condition"]),
               int(rule.get("enabled", True)), rid, user_id))
    return get_rule(rid, user_id)


def delete_rule(rid, user_id):
    with _db(write=True) as c:
        cur = _exec(c, "DELETE FROM rules WHERE id=? AND user_id=?", (rid, user_id))
        # only clear dedup state if OUR row actually went: an unscoped delete here
        # lets a foreign delete attempt un-latch someone else's rule and re-alert them
        if cur.rowcount:
            _exec(c, "DELETE FROM rule_state WHERE rule_id=?", (rid,))


def record_transition(rule_id, fired, value):
    """Persist fired-state; return True only on a fresh False->True edge (a new alert).

    The edge is claimed by an UPDATE guarded on `fired=0`, so exactly one caller
    can win it even if two evaluation cycles overlap.
    """
    now = datetime.now(ET).isoformat()
    with _db(write=True) as c:
        _exec(c, "INSERT INTO rule_state(rule_id,fired,last_value) VALUES(?,0,NULL) "
                 "ON CONFLICT(rule_id) DO NOTHING", (rule_id,))
        if not fired:
            _exec(c, "UPDATE rule_state SET fired=0,last_value=? WHERE rule_id=?", (value, rule_id))
            return False
        cur = _exec(c, "UPDATE rule_state SET fired=1,last_value=?,last_fired_at=? "
                       "WHERE rule_id=? AND fired=0", (value, now, rule_id))
        if cur.rowcount == 1:
            return True
        _exec(c, "UPDATE rule_state SET last_value=? WHERE rule_id=?", (value, rule_id))
        return False


def append_alert(rule, description, value, price):
    # rule["user_id"], not .get(): an alert with no owner is one nobody can ever
    # see, and it should fail in tests rather than vanish in production.
    with _db(write=True) as c:
        _exec(c,
              "INSERT INTO alerts(user_id,rule_id,name,symbol,timeframe,description,value,price,ts,ts_ms) "
              "VALUES(?,?,?,?,?,?,?,?,?,?)",
              (rule["user_id"], rule["id"], rule["name"], rule["symbol"], rule["timeframe"],
               description, value, price,
               datetime.now(ET).strftime("%Y-%m-%d %H:%M:%S ET"), int(time.time() * 1000)))


def list_alerts(user_id, limit=50):
    limit = max(1, min(int(limit), 500))  # bounded: the table grows without limit
    with _db() as c:
        return [dict(r) for r in _exec(
            c, "SELECT * FROM alerts WHERE user_id=? ORDER BY id DESC LIMIT ?", (user_id, limit))]


# --- dead-man heartbeat ----------------------------------------------------
# Lives in the DB, not a module global: on serverless every request is a fresh
# process, and an in-memory heartbeat would reset to "healthy" on every cold
# start — a permanently green lie about a monitor that stopped running.

def mark_success():
    set_setting("last_success_ms", int(time.time() * 1000))


def last_success_ms():
    v = get_setting("last_success_ms")
    return int(v) if v else None


def stale_seconds():
    """Seconds since the last healthy cycle, or None if one has never landed."""
    ms = last_success_ms()
    return None if ms is None else max(0.0, time.time() - ms / 1000.0)
